import { AuthRepository } from './AuthRepository'
import { tokenManager } from './tokenManager'
import { ROLES, ROLE_LABELS } from '../../config/constants'
import { getDefaultRoute } from '../../app/authRoutes'

const ROLE_CODES = { citizen: ROLES.CITIZEN, citizen_registered: ROLES.CITIZEN, citizen_anonymous: ROLES.CITIZEN, department_officer: ROLES.DEPT_OFFICER, dept_officer: ROLES.DEPT_OFFICER, department_head: ROLES.DEPT_HEAD, dept_head: ROLES.DEPT_HEAD, executive_engineer: ROLES.ENGINEER, engineer: ROLES.ENGINEER, field_inspector: ROLES.FIELD_INSPECTOR, field_supervisor: ROLES.SUPERVISOR, adm: ROLES.ADM, district_magnetrate: ROLES.DM, district_magistrate: ROLES.DM, dm: ROLES.DM, collector: ROLES.DISTRICT_COLLECTOR, district_collector: ROLES.DISTRICT_COLLECTOR, state_admin: ROLES.STATE_ADMIN, system_admin: ROLES.SYSTEM_ADMIN }
export function normalizeUser(profile = {}) { const department = profile.department || profile.department_id || {}; const district = profile.district || profile.district_id || {}; const code = String(profile.role_info?.code || profile.role?.code || profile.role_code || profile.role || '').toLowerCase().replace(/[\s-]/g, '_'); const role = ROLE_CODES[code]; if (!role) throw new Error('Your account does not have a recognised NDISP role. Please contact an administrator.'); const departmentName = String(profile.department_name || (typeof department === 'object' ? department.name || department.label : '') || '').trim(); const roleName = String(profile.role_info?.name || profile.role?.name || profile.designation || ROLE_LABELS[role] || role).trim(); return { id: profile.id || profile.user_id, username: profile.username, email: profile.email, name: profile.full_name || profile.name || [profile.first_name, profile.last_name].filter(Boolean).join(' ') || profile.username, role, roleCode: code, roleName, departmentId: department?.id || department || null, departmentName, department: typeof department === 'object' ? department : profile.department_name ? { label: profile.department_name } : null, districtId: district?.id || district || null, district: typeof district === 'object' ? district : profile.district_name ? { label: profile.district_name } : null, designation: profile.designation || '', permissions: profile.permissions || profile.role_info?.permissions || [] } }
export const AuthService = {
  async login(credentials) { await AuthRepository.login(credentials); const user = normalizeUser(await AuthRepository.getCurrentUser()); tokenManager.setUser(user); return { user, redirectTo: getDefaultRoute(user.role) } },
  async signup(payload) { return AuthRepository.signup(payload) },
  async restoreSession() { if (!tokenManager.get().access && !tokenManager.get().refresh) return null; const user = normalizeUser(await AuthRepository.getCurrentUser()); tokenManager.setUser(user); return user },
  logout() { AuthRepository.logout() },
}
