import { useMemo, useState } from 'react'
import { FileDown, FileText, FileSpreadsheet, Map as MapIcon, Loader2, RefreshCw, CheckCircle2, AlertCircle } from 'lucide-react'
import PageHeader from '../../components/ui/PageHeader'
import { Card, CardBody, CardHeader } from '../../components/ui/Card'
import Button from '../../components/ui/Button'
import Badge from '../../components/ui/Badge'
import { useUiStore } from '../../app/store/uiStore'
import { analyticsApi } from '../../services/api'
import { useAuthStore } from '../../app/store/authStore'
import { useAsync } from '../../hooks/useAsync'
import BudgetBarChart from '../../components/charts/BudgetBarChart'
import { backendReportApi } from '../../api/reportApi'

const REPORT_TYPES = [
  { type: 'sla_audit', label: 'SLA Audit Report', icon: FileText, format: 'PDF', description: 'SLA breach rate, resolution speed, escalation metrics.' },
  { type: 'asset_audit', label: 'Asset Geotag Verification', icon: FileSpreadsheet, format: 'CSV', description: 'Geotagged facility & asset verification logs.' },
  { type: 'grievance', label: 'Grievance Resolution Summary', icon: FileText, format: 'PDF', description: 'Citizen complaint volume, status breakdown, satisfaction.' },
  { type: 'workflow', label: 'Workflow & Operations Audit', icon: MapIcon, format: 'PDF', description: 'Immutable audit logs of state machine transitions.' },
]

export default function AdminReports() {
  const user = useAuthStore((s) => s.user)
  const pushToast = useUiStore((s) => s.pushToast)
  const [generating, setGenerating] = useState(null)
  const [downloadId, setDownloadId] = useState(null)
  const [actionError, setActionError] = useState(null)

  const { data: budget } = useAsync(() => analyticsApi.getBudgetUtilization(user?.districtId), [user?.districtId])

  const listFetcher = useMemo(() => () => backendReportApi.list(), [])
  const { data: reports, loading: listLoading, error: listError, refetch } = useAsync(listFetcher, [])

  const handleGenerate = async (type) => {
    setGenerating(type)
    setActionError(null)
    try {
      const result = await backendReportApi.generate({ type, department: user?.departmentId || 1 })
      pushToast(`Report ${result.report.code} generated — ${result.message || 'success'}.`, 'success')
      refetch()
    } catch (e) {
      const msg = e?.message || 'Generation failed'
      if (e?.status === 400) pushToast(`Invalid request: ${msg}`, 'error')
      else if (e?.status === 401 || e?.status === 403) pushToast(`Permission denied: ${msg}`, 'error')
      else if (e?.status === 404) pushToast(`Report type not found: ${msg}`, 'error')
      else if (e?.status === 500) pushToast(`Backend error: ${msg}`, 'error')
      else pushToast(`Generation failed: ${msg}`, 'error')
      setActionError(e)
    } finally {
      setGenerating(null)
    }
  }

  const handleDownload = async (report) => {
    setDownloadId(report.id)
    setActionError(null)
    try {
      const { blob, filename } = await backendReportApi.download(report.id)
      const url = URL.createObjectURL(blob)
      const anchor = document.createElement('a')
      anchor.href = url
      anchor.download = filename || `${report.code}.${(report.format || 'pdf').toLowerCase()}`
      document.body.appendChild(anchor)
      anchor.click()
      anchor.remove()
      URL.revokeObjectURL(url)
      pushToast(`Report ${report.code} downloaded.`, 'success')
    } catch (e) {
      const msg = e?.message || 'Download failed'
      if (e?.status === 404) pushToast(`File not available: ${msg}. The report may still be generating.`, 'warning')
      else pushToast(`Download failed: ${msg}`, 'error')
      setActionError(e)
    } finally {
      setDownloadId(null)
    }
  }

  return (
    <div>
      <PageHeader eyebrow="Admin Portal · FR-XC-03" title="Reports & exports" description="Generate, manage and download official district reports. All reports are generated by the backend reporting service." />
      <div className="px-6 pb-8 space-y-6">
        <Card>
          <CardHeader title="Budget utilization by department" subtitle="Sanctioned vs. utilized, current fiscal year" />
          <CardBody>{budget ? <BudgetBarChart data={budget} /> : <div className="h-64" />}</CardBody>
        </Card>

        {/* Report Generation */}
        <Card>
          <CardHeader title="Generate new report" subtitle="Select a report type to generate via the backend reporting service" />
          <CardBody className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {REPORT_TYPES.map((r) => (
              <div key={r.type} className="flex items-center gap-3.5 rounded-xl border border-ink-200 bg-white p-3.5">
                <div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-ink-100 text-ink-700"><r.icon size={17} /></div>
                <div className="flex-1 min-w-0">
                  <p className="text-[13px] font-semibold text-ink-950">{r.label}</p>
                  <p className="text-[11px] text-ink-500">{r.description}</p>
                  <p className="text-[10.5px] text-ink-400 mt-0.5">Format: {r.format}</p>
                </div>
                <Button size="sm" variant="outline" icon={generating === r.type ? Loader2 : FileDown} loading={generating === r.type} onClick={() => handleGenerate(r.type)}>
                  Generate
                </Button>
              </div>
            ))}
          </CardBody>
        </Card>

        {/* Generated Reports Catalog */}
        <Card>
          <CardHeader
            title="Generated reports"
            subtitle={reports ? `${reports.length} report(s) available` : 'Loading…'}
            action={<Button size="sm" variant="outline" icon={RefreshCw} onClick={refetch}>Refresh</Button>}
          />
          <CardBody className="!p-0">
            {listLoading && (
              <div className="flex items-center gap-2 p-6 text-[12.5px] text-ink-500">
                <Loader2 size={14} className="animate-spin" /> Loading report catalog…
              </div>
            )}
            {listError && (
              <div className="flex items-center gap-2 p-6 text-[12.5px] text-alert-600">
                <AlertCircle size={14} /> Failed to load reports: {listError.message}
              </div>
            )}
            {!listLoading && !listError && reports && reports.length === 0 && (
              <div className="flex items-center gap-2 p-6 text-[12.5px] text-ink-500">
                No reports generated yet. Use the generate buttons above to create your first report.
              </div>
            )}
            {reports && reports.length > 0 && (
              <div className="divide-y divide-ink-50">
                {reports.map((rpt) => (
                  <div key={rpt.id} className="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 hover:bg-ink-50/50 transition-colors">
                    <div className="space-y-1 min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="kbd-mono text-[11px] text-ink-400">{rpt.code}</span>
                        <h4 className="text-[13px] font-semibold text-ink-950">{rpt.title}</h4>
                        <Badge tone="neutral">{rpt.format}</Badge>
                      </div>
                      <div className="flex items-center gap-4 text-[11px] text-ink-400">
                        <span>{rpt.category}</span>
                        <span>{rpt.departmentName}</span>
                        {rpt.districtName && <span>{rpt.districtName}</span>}
                        <span>{rpt.fileSize}</span>
                        {rpt.generatedAt && <span>{new Date(rpt.generatedAt).toLocaleDateString()}</span>}
                        {rpt.generatedBy && <span>by {rpt.generatedBy}</span>}
                      </div>
                    </div>
                    <Button size="sm" variant="outline" icon={downloadId === rpt.id ? Loader2 : FileDown} loading={downloadId === rpt.id} onClick={() => handleDownload(rpt)}>
                      Download
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      </div>
    </div>
  )
}
