// Revenue & Property Intelligence — Components Index (New Tax & Revenue Module)

export { RevenueHeader } from './RevenueHeader'
export { RevenueMapWorkspace } from './RevenueMapWorkspace'
export { RevenueLayerSidebar } from './RevenueLayerSidebar'
export { PayTaxModal } from './PayTaxModal'
export { TaxListModal } from './TaxListModal'
export { SpatialQueryModal } from './SpatialQueryModal'
export { GeotagVerificationModal } from './GeotagVerificationModal'
export { DdssDashboardModal } from './DdssDashboardModal'

// Legacy components (kept for compatibility during transition)
export { default as RevenueKpiCards } from './RevenueKpiCards'
export { default as RevenueMap } from './RevenueMap'
export { default as RevenueMapToolbar } from './RevenueMapToolbar'
export { default as RevenueLayerManager } from './RevenueLayerManager'
export { default as PropertyMapPopup } from './PropertyMapPopup'
export { default as PropertyResultList } from './PropertyResultList'
export { default as RevenueFilters } from './RevenueFilters'
export { default as PropertyDrawer } from './PropertyDrawer'
export { default as AssessmentPanel } from './AssessmentPanel'
export { default as DemandPanel } from './DemandPanel'
export { default as PaymentHistory } from './PaymentHistory'
export { default as ArrearsPanel } from './ArrearsPanel'
export { default as RevenueActionMenu } from './RevenueActionMenu'
export { RevenueHeatmapLegend, RevenueHeatmapLegendHorizontal } from './RevenueHeatmapLegend'
export { RevenueMapLegend, RevenueMapLegendHorizontal } from './RevenueMapLegend'
export { RevenueModeSelector } from './RevenueModeSelector'
export { AreaIntelligencePanel } from './AreaIntelligencePanel'
export { RevenueInsightsPanel } from './RevenueInsightsPanel'
export { CollectionTrendChart } from './CollectionTrendChart'
export { ArrearsAgingChart } from './ArrearsAgingChart'
export { PropertyDistributionChart } from './PropertyDistributionChart'
export { BlockPerformanceTable } from './BlockPerformanceTable'
export { ReviewCandidatesPanel } from './ReviewCandidatesPanel'
export { RevenueAnalyticsPanel } from './RevenueAnalyticsPanel'
export { PropertyCommandDrawer } from './PropertyCommandDrawer'
export { RevenueCommandWorkspace } from './RevenueCommandWorkspace'
export { PaymentDialog } from './PaymentDialog'
export { TaxRegisterModal } from './TaxRegisterModal'
export { TaxSearchModal } from './TaxSearchModal'