import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardList, FilePlus2, Landmark, MapPin, Send, Sparkles } from 'lucide-react'
import PageHeader from '../../../components/ui/PageHeader'
import DataTable from '../../../components/ui/DataTable'
import Badge from '../../../components/ui/Badge'
import Button from '../../../components/ui/Button'
import StatCard from '../../../components/ui/StatCard'
import { Card, CardBody, CardHeader } from '../../../components/ui/Card'
import { useDepartment } from '../framework/DepartmentContext'
import { useCurrentUser, useCan } from '../identity/hooks/useAuthorization'
import { ProposalAnalyticsRepository } from '../repositories/ProposalAnalyticsRepository'
import { PlanningRepository } from '../repositories/PlanningRepository'
import { ProposalRepository } from '../repositories/ProposalRepository'
import { formatCurrencyINR } from '../../../utils/format'
import { useProjectEngine } from '../../../app/store/projectEngine'

const STEPS = ['Need identification', 'Survey & inspection', 'Technical DPR', 'Financial estimation', 'Clearances', 'Attachments', 'Review & submit']
const inputClass = 'w-full rounded-lg border border-ink-200 px-3 py-2 text-sm outline-none focus:border-sky-500'
const label = (text) => <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-ink-500">{text}</label>

function DprWizard({ need, onClose }) {
  const { dept } = useDepartment(); const user = useCurrentUser(); const [step, setStep] = useState(0)
  const [form, setForm] = useState({ title: need?.title || '', category: 'Infrastructure', priority: need?.priority || 'medium', problemStatement: '', linkedComplaints: need?.complaintId || '', village: need?.village || '', block: need?.block || 'Silao', ward: '', population: need?.population || '', gapScore: need?.gapScore || '', surveyNotes: '', surveyDate: '', technicalScope: '', engineeringNotes: '', timeline: '90 days', civilWorks: '', equipment: '', electrical: '', contingency: '', maintenance: '', fundingSource: 'District', clearances: '', attachments: '' })
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const total = ['civilWorks', 'equipment', 'electrical', 'contingency', 'maintenance'].reduce((sum, key) => sum + Number(form[key] || 0), 0)
  const save = (state) => { const proposal = ProposalRepository.create({ ...form, departmentId: dept.id, creatorName: user?.name, description: form.problemStatement, needAssessment: form.problemStatement, financialEstimate: total, fundingSource: form.fundingSource, supportingDocuments: form.attachments ? form.attachments.split(',').map((item) => item.trim()) : [], gisLocation: { position: [85.4211, 25.0294], address: `${form.village}, ${form.block}` } }); if (state !== 'draft') ProposalRepository.transition(proposal.id, 'department_review', user, 'DPR submitted to Department Head for review.'); onClose() }
  const page = [
    <div className="grid gap-3 sm:grid-cols-2" key="need">{[['Proposal title', 'title'], ['Category', 'category'], ['Village', 'village'], ['Block', 'block'], ['Ward', 'ward'], ['Population impact', 'population'], ['Gap score', 'gapScore'], ['Linked complaint IDs', 'linkedComplaints']].map(([name, key]) => <div key={key}>{label(name)}<input className={inputClass} value={form[key]} onChange={(e) => update(key, e.target.value)} /></div>)}<div>{label('Priority')}<select className={inputClass} value={form.priority} onChange={(e) => update('priority', e.target.value)}><option>low</option><option>medium</option><option>high</option><option>urgent</option></select></div><div className="sm:col-span-2">{label('Problem statement and reason')}<textarea className={inputClass} rows="3" value={form.problemStatement} onChange={(e) => update('problemStatement', e.target.value)} /></div></div>,
    <div className="grid gap-3 sm:grid-cols-2" key="survey"><div>{label('Inspection date')}<input type="date" className={inputClass} value={form.surveyDate} onChange={(e) => update('surveyDate', e.target.value)} /></div><div>{label('Survey team')}<input className={inputClass} placeholder="Officer, engineer, inspector" /></div><div className="sm:col-span-2">{label('Inspection notes / existing infrastructure')}<textarea className={inputClass} rows="5" value={form.surveyNotes} onChange={(e) => update('surveyNotes', e.target.value)} placeholder="Coverage, catchment radius, nearby assets and survey result" /></div><div className="sm:col-span-2 rounded-lg border border-sky-100 bg-sky-50 p-4 text-sm text-sky-800"><MapPin className="mr-2 inline" size={16} />GIS reference: {form.village || 'Selected site'}, {form.block}</div></div>,
    <div className="grid gap-3" key="technical"><div>{label('Technical scope')}<textarea className={inputClass} rows="3" value={form.technicalScope} onChange={(e) => update('technicalScope', e.target.value)} placeholder="Scope, execution method, specifications and material requirements" /></div><div>{label('Engineering notes and dependencies')}<textarea className={inputClass} rows="3" value={form.engineeringNotes} onChange={(e) => update('engineeringNotes', e.target.value)} /></div><div>{label('Estimated timeline')}<input className={inputClass} value={form.timeline} onChange={(e) => update('timeline', e.target.value)} /></div></div>,
    <div className="grid gap-3 sm:grid-cols-2" key="financial">{[['Civil works', 'civilWorks'], ['Equipment', 'equipment'], ['Electrical', 'electrical'], ['Contingency', 'contingency'], ['Maintenance', 'maintenance']].map(([name, key]) => <div key={key}>{label(name)}<input type="number" min="0" className={inputClass} value={form[key]} onChange={(e) => update(key, e.target.value)} /></div>)}<div className="rounded-lg bg-ink-900 p-4 text-white"><span className="text-xs uppercase text-ink-300">Grand total</span><div className="text-xl font-bold">{formatCurrencyINR(total)}</div><small>{total <= 5000000 ? 'Within DM delegated power' : 'Requires State approval'}</small></div></div>,
    <div className="grid gap-3" key="clearance"><div>{label('Funding source')}<select className={inputClass} value={form.fundingSource} onChange={(e) => update('fundingSource', e.target.value)}>{['District', 'State', 'Central', 'CSR', 'World Bank', 'ADB', 'Other'].map((option) => <option key={option}>{option}</option>)}</select></div><div>{label('Clearances and NOCs')}<textarea className={inputClass} rows="5" value={form.clearances} onChange={(e) => update('clearances', e.target.value)} placeholder="Environmental, land, forest, utility shifting, NOC" /></div></div>,
    <div key="attachments">{label('Attachment register')}<textarea className={inputClass} rows="6" value={form.attachments} onChange={(e) => update('attachments', e.target.value)} placeholder="Survey PDF, DPR, estimate, CAD drawing, photos, tender draft (comma separated)" /><p className="mt-2 text-xs text-ink-400">Files are represented as repository records in this simulation frontend.</p></div>,
    <div className="space-y-3" key="review"><div className="rounded-xl border border-ink-150 p-4 text-sm"><strong>{form.title || 'Untitled DPR'}</strong><p className="mt-2 text-ink-600">{form.problemStatement || 'No need assessment entered.'}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>Priority: <b>{form.priority}</b></span><span>Funding: <b>{form.fundingSource}</b></span><span>Beneficiaries: <b>{form.population || '—'}</b></span><span>Cost: <b>{formatCurrencyINR(total)}</b></span></div></div><p className="text-sm text-ink-500">Submitting sends this DPR to the Department Head. Only district sanction will create a project.</p></div>,
  ][step]
  return <div className="space-y-5"><div className="flex flex-wrap gap-1">{STEPS.map((name, index) => <span key={name} className={`rounded-full px-2 py-1 text-[10px] ${index === step ? 'bg-sky-600 text-white' : index < step ? 'bg-leaf-100 text-leaf-800' : 'bg-ink-100 text-ink-400'}`}>{index + 1}. {name}</span>)}</div>{page}<div className="flex justify-between border-t border-ink-100 pt-4"><Button variant="ghost" icon={ArrowLeft} disabled={!step} onClick={() => setStep(step - 1)}>Back</Button>{step < STEPS.length - 1 ? <Button icon={ArrowRight} onClick={() => setStep(step + 1)}>Continue</Button> : <span className="flex gap-2"><Button variant="outline" onClick={() => save('draft')}>Save draft</Button><Button variant="positive" icon={Send} onClick={() => save('submitted')}>Submit to head</Button></span>}</div></div>
}

export default function DepartmentPlanningWorkspace({ view = 'dashboard' }) {
  const { dept, complaints } = useDepartment(); const user = useCurrentUser(); const canCreate = useCan('projects.create'); const [wizard, setWizard] = useState(false); const [need, setNeed] = useState(null)
  const allProposals = useProjectEngine((state) => state.proposals)
  const proposals = useMemo(() => allProposals.filter((item) => item.departmentId === dept.id), [allProposals, dept.id])
  const stats = ProposalAnalyticsRepository.summarize(proposals); const needs = useMemo(() => PlanningRepository.developmentNeeds(dept.id, complaints), [dept.id, complaints])
  const filter = { drafts: ['draft'], submitted: ['department_review', 'dm_review', 'submitted', 'collector'], returned: ['returned'], approved: ['approved'], rejected: ['rejected'] }[view]
  const rows = filter ? proposals.filter((item) => filter.includes(item.state)) : proposals
  const decide = (proposal, state) => ProposalRepository.transition(proposal.id, state, user, state === 'dm_review' ? 'Department review approved; forwarded to DM.' : 'Returned for DPR correction.')
  if (wizard || view === 'new') return <div className="space-y-6 pb-8"><PageHeader eyebrow={`${dept.code} · Planning & Proposals`} title="Development Proposal DPR Wizard" description="Prepare a traceable, sanction-ready Department Project Report." action={<Button variant="outline" onClick={() => { setWizard(false); window.history.back() }}>Cancel</Button>} /><div className="px-6"><Card><CardBody><DprWizard need={need} onClose={() => { setWizard(false); setNeed(null) }} /></CardBody></Card></div></div>
  return <div className="space-y-6 pb-8"><PageHeader eyebrow={`${dept.code} · Planning & Proposals`} title={view === 'dashboard' ? 'Development Planning ERP' : `${view[0].toUpperCase()}${view.slice(1)} Proposals`} description="Development needs flow through DPR, department review, DM sanction and automatic project creation." action={canCreate && <Button icon={FilePlus2} onClick={() => setWizard(true)}>New proposal</Button>} />{view === 'dashboard' && <><div className="px-6 grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Development Needs" value={needs.length} icon={Sparkles} tone="saffron" /><StatCard label="Draft DPR" value={stats.draft} icon={ClipboardList} tone="ink" /><StatCard label="Pending Review" value={stats.review} icon={Landmark} tone="sky" /><StatCard label="Approved" value={stats.approved} icon={CheckCircle2} tone="leaf" /></div><div className="px-6"><Card><CardHeader title="Suggested development needs" subtitle="Simulation-derived complaint clusters and infrastructure gaps" icon={Sparkles} /><CardBody className="!p-0"><DataTable rows={needs} columns={[{ key: 'title', label: 'Need' }, { key: 'village', label: 'Village' }, { key: 'gapScore', label: 'Gap score' }, { key: 'priority', label: 'Priority', render: (row) => <Badge tone={row.priority === 'urgent' ? 'negative' : 'warning'}>{row.priority}</Badge> }, { key: 'convert', label: '', render: (row) => canCreate && <Button size="sm" variant="outline" onClick={() => { setNeed(row); setWizard(true) }}>Convert to DPR</Button> }]} emptyLabel="No priority development needs right now" /></CardBody></Card></div></>}<div className="px-6"><Card><CardHeader title="DPR repository" subtitle={`${rows.length} proposals in this view`} icon={ClipboardList} /><CardBody className="!p-0"><DataTable rows={rows} columns={[{ key: 'id', label: 'Proposal ID' }, { key: 'title', label: 'DPR title' }, { key: 'financialEstimate', label: 'Cost', render: (row) => formatCurrencyINR(row.financialEstimate || 0) }, { key: 'state', label: 'Status', render: (row) => <Badge tone={row.state === 'approved' ? 'positive' : row.state === 'returned' ? 'warning' : row.state === 'rejected' ? 'negative' : 'info'}>{row.state.replace(/_/g, ' ')}</Badge> }, { key: 'action', label: 'Review', render: (row) => user?.role === 'dept_head' && row.state === 'department_review' ? <span className="flex gap-1"><Button size="sm" variant="positive" onClick={() => decide(row, 'dm_review')}>Forward DM</Button><Button size="sm" variant="outline" onClick={() => decide(row, 'returned')}>Return</Button></span> : '—' }]} emptyLabel="No proposals in this workflow stage" /></CardBody></Card></div></div>
}
