import { useMemo, useState } from 'react'
import { Activity, Check, Clock3, FileClock, Plus, ShieldCheck, UserCog, Users } from 'lucide-react'
import PageHeader from '../../../components/ui/PageHeader'
import DataTable from '../../../components/ui/DataTable'
import Badge from '../../../components/ui/Badge'
import Button from '../../../components/ui/Button'
import Modal from '../../../components/ui/Modal'
import { Card, CardBody, CardHeader } from '../../../components/ui/Card'
import { useDepartment } from '../framework/DepartmentContext'
import { useAuthorization } from '../identity/hooks/useAuthorization'
import { useIdentityStore } from '../identity/identityStore'
import { PERMISSION_CATALOG } from '../identity/permissions/permissionCatalog'

const label = (value = '') => value.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const statusTone = (status) => ({ active: 'positive', present: 'positive', approved: 'positive', pending: 'warning', suspended: 'negative', rejected: 'negative', offline: 'neutral', field: 'info' }[status] || 'neutral')

export default function DepartmentWorkforceWorkspace({ mode = 'employees' }) {
  const { dept } = useDepartment()
  const { user, can } = useAuthorization()
  const employees = useIdentityStore((state) => state.employees)
  const roles = useIdentityStore((state) => state.roles)
  const attendance = useIdentityStore((state) => state.attendance)
  const leaves = useIdentityStore((state) => state.leaves)
  const tasks = useIdentityStore((state) => state.tasks)
  const auditLogs = useIdentityStore((state) => state.auditLogs)
  const onboardEmployee = useIdentityStore((state) => state.onboardEmployee)
  const updateEmployee = useIdentityStore((state) => state.updateEmployee)
  const updateRolePermissions = useIdentityStore((state) => state.updateRolePermissions)
  const clock = useIdentityStore((state) => state.clock)
  const decideLeave = useIdentityStore((state) => state.decideLeave)
  const [query, setQuery] = useState('')
  const [inviteOpen, setInviteOpen] = useState(false)
  const [selectedRole, setSelectedRole] = useState(roles[0]?.id)
  const [form, setForm] = useState({ name: '', email: '', designation: '', role: 'dept_officer', office: 'District Office', block: 'Silao', managerId: '' })

  const staff = useMemo(() => employees.filter((item) => item.departmentId === dept.id), [employees, dept.id])
  const filteredStaff = useMemo(() => staff.filter((item) => `${item.name} ${item.email} ${item.designation}`.toLowerCase().includes(query.toLowerCase())), [staff, query])
  const title = { employees: 'Employee Directory', organization: 'Organization Hierarchy', roles: 'Department Role Builder', permissions: 'Permission Matrix', attendance: 'Attendance Management', leave: 'Leave Management', performance: 'Performance Management', audit: 'Security Audit Trail' }[mode]
  const description = { employees: 'Onboard, search and manage employees within this department.', organization: 'Review reporting relationships and departmental span of control.', roles: 'Configure reusable department roles and assign access profiles.', permissions: 'Configure the actions granted to each departmental role.', attendance: 'Live clock events, field status and daily workforce presence.', leave: 'Review employee leave applications and approval decisions.', performance: 'Operational performance signals derived from attendance and assigned work.', audit: 'Immutable event history for workforce and authorization activity.' }[mode]
  const actor = user || { name: 'Department Administrator', id: 'system' }
  const submitInvite = (event) => { event.preventDefault(); onboardEmployee(actor, { ...form, departmentId: dept.id, managerId: form.managerId || null }); setInviteOpen(false); setForm({ name: '', email: '', designation: '', role: 'dept_officer', office: 'District Office', block: 'Silao', managerId: '' }) }
  const pendingLeaves = leaves.filter((item) => staff.some((employee) => employee.id === item.employeeId))

  const employeeColumns = [
    { key: 'name', label: 'Employee', render: (row) => <div><div className="font-semibold text-ink-950">{row.name}</div><div className="text-[11px] text-ink-400">{row.employeeNumber} · {row.email}</div></div> },
    { key: 'designation', label: 'Designation', render: (row) => <span>{row.designation || label(row.role)}</span> },
    { key: 'office', label: 'Office / Block', render: (row) => <span>{row.office || '—'}<br /><small className="text-ink-400">{row.block || '—'}</small></span> },
    { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{label(row.status)}</Badge> },
    { key: 'action', label: 'Action', render: (row) => can('workforce.manage') && <Button size="sm" variant="outline" onClick={(event) => { event.stopPropagation(); updateEmployee(actor, row.id, { status: row.status === 'active' ? 'suspended' : 'active' }) }}>{row.status === 'active' ? 'Suspend' : 'Activate'}</Button> },
  ]

  const renderEmployees = () => <Card><CardHeader title="Department employees" subtitle={`${staff.length} registered workforce members`} icon={Users} action={can('workforce.invite') && <Button icon={Plus} size="sm" onClick={() => setInviteOpen(true)}>Invite employee</Button>} /><CardBody className="!p-0"><div className="p-3 border-b border-ink-100"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email or designation" className="w-full rounded-lg border border-ink-200 px-3 py-2 text-sm outline-none focus:border-sky-500" /></div><DataTable rows={filteredStaff} columns={employeeColumns} emptyLabel="No employees match this search" /></CardBody></Card>
  const renderOrganization = () => <Card><CardHeader title="Reporting hierarchy" subtitle="Employees without a manager report to the department head." icon={UserCog} /><CardBody><div className="space-y-3">{staff.length ? staff.filter((person) => !person.managerId).map((manager) => <div key={manager.id} className="rounded-lg border border-ink-150 p-3"><div className="font-semibold text-ink-950">{manager.name} <span className="font-normal text-ink-400">— {manager.designation || label(manager.role)}</span></div><div className="mt-2 ml-4 space-y-1 border-l-2 border-sky-100 pl-3">{staff.filter((person) => person.managerId === manager.id).map((person) => <div key={person.id} className="text-sm text-ink-700">{person.name} <span className="text-ink-400">· {person.designation || label(person.role)}</span></div>)}{!staff.some((person) => person.managerId === manager.id) && <div className="text-xs text-ink-400">No direct reports</div>}</div></div>) : <p className="text-sm text-ink-400">Invite employees to establish the reporting hierarchy.</p>}</div></CardBody></Card>
  const renderRoles = () => <Card><CardHeader title="Role profiles" subtitle="System roles can be tailored through the permission matrix." icon={ShieldCheck} /><CardBody><div className="grid gap-3 md:grid-cols-2">{roles.map((role) => <div key={role.id} className="rounded-lg border border-ink-150 p-4"><div className="flex justify-between"><strong className="text-ink-950">{label(role.name)}</strong><Badge tone={role.system ? 'info' : 'neutral'}>{role.system ? 'System role' : 'Custom role'}</Badge></div><p className="mt-2 text-xs text-ink-500">{role.permissions.length} enabled permissions · {staff.filter((person) => person.role === role.id).length} assigned users</p></div>)}</div></CardBody></Card>
  const renderPermissions = () => { const role = roles.find((item) => item.id === selectedRole) || roles[0]; const selected = new Set(role?.permissions || []); return <Card><CardHeader title="Role permission matrix" subtitle="Changes are audited and apply immediately to the selected role." icon={ShieldCheck} action={<select value={role?.id || ''} onChange={(event) => setSelectedRole(event.target.value)} className="rounded-lg border border-ink-200 px-2 py-1.5 text-sm">{roles.map((item) => <option key={item.id} value={item.id}>{label(item.name)}</option>)}</select>} /><CardBody><div className="space-y-4">{Object.entries(PERMISSION_CATALOG).map(([module, actions]) => <div key={module} className="rounded-lg border border-ink-100 p-3"><div className="mb-2 text-sm font-semibold text-ink-900">{label(module)}</div><div className="flex flex-wrap gap-2">{actions.map((action) => { const permission = `${module}.${action}`; return <button type="button" key={permission} disabled={!can('workforce.roles')} onClick={() => updateRolePermissions(actor, role.id, selected.has(permission) ? role.permissions.filter((item) => item !== permission) : [...role.permissions, permission])} className={`rounded-md border px-2 py-1 text-xs ${selected.has(permission) ? 'border-sky-300 bg-sky-50 text-sky-800' : 'border-ink-200 text-ink-500'}`}>{selected.has(permission) && <Check size={11} className="mr-1 inline" />}{label(action)}</button> })}</div></div>)}</div></CardBody></Card> }
  const renderAttendance = () => <Card><CardHeader title="Today’s attendance" subtitle="Clock in/out events can include GPS data when enabled." icon={Clock3} /><CardBody className="!p-0"><DataTable rows={staff} columns={[{ key: 'name', label: 'Employee' }, { key: 'attendanceStatus', label: 'Live status', render: (row) => <Badge tone={statusTone(row.attendanceStatus)}>{label(row.attendanceStatus || 'offline')}</Badge> }, { key: 'last', label: 'Last event', render: (row) => attendance.find((item) => item.employeeId === row.id)?.timestamp ? new Date(attendance.find((item) => item.employeeId === row.id).timestamp).toLocaleString() : 'No event today' }, { key: 'clock', label: 'Action', render: (row) => <Button size="sm" variant="outline" disabled={!can('workforce.attendance')} onClick={() => clock(actor, row.id, row.attendanceStatus === 'field' ? 'clock_out' : 'clock_in', { source: 'web', departmentId: dept.id })}>{row.attendanceStatus === 'field' ? 'Clock out' : 'Clock in'}</Button> }]} emptyLabel="No employees available" /></CardBody></Card>
  const renderLeave = () => <Card><CardHeader title="Leave approval queue" subtitle="Applications and decisions form part of the workforce audit trail." icon={FileClock} /><CardBody className="!p-0"><DataTable rows={pendingLeaves} columns={[{ key: 'employeeId', label: 'Employee', render: (row) => staff.find((person) => person.id === row.employeeId)?.name || row.employeeId }, { key: 'type', label: 'Leave type', render: (row) => label(row.type) }, { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{label(row.status)}</Badge> }, { key: 'action', label: 'Decision', render: (row) => row.status === 'pending' && <span className="flex gap-2"><Button size="sm" variant="positive" disabled={!can('workforce.leave')} onClick={() => decideLeave(actor, row.id, 'approved')}>Approve</Button><Button size="sm" variant="outline" disabled={!can('workforce.leave')} onClick={() => decideLeave(actor, row.id, 'rejected')}>Reject</Button></span> }]} emptyLabel="No leave applications" /></CardBody></Card>
  const renderPerformance = () => <Card><CardHeader title="Workforce performance" subtitle="A simple live score based on completed tasks and attendance events." icon={Activity} /><CardBody className="!p-0"><DataTable rows={staff.map((person) => { const ownTasks = tasks.filter((task) => task.assigneeId === person.id); const completed = ownTasks.filter((task) => ['completed', 'verified', 'closed'].includes(task.status)).length; const days = attendance.filter((event) => event.employeeId === person.id && event.type === 'clock_in').length; return { ...person, completed, days, score: Math.min(100, 55 + completed * 8 + days * 2) } }).sort((a, b) => b.score - a.score)} columns={[{ key: 'name', label: 'Employee' }, { key: 'completed', label: 'Tasks completed' }, { key: 'days', label: 'Attendance days' }, { key: 'score', label: 'Efficiency score', render: (row) => <span className="font-semibold text-leaf-700">{row.score}%</span> }]} emptyLabel="No performance data" /></CardBody></Card>
  const renderAudit = () => <Card><CardHeader title="Immutable workforce audit log" subtitle="Event records include actor, module, action and timestamp." icon={FileClock} /><CardBody className="!p-0"><DataTable rows={auditLogs} columns={[{ key: 'timestamp', label: 'Timestamp', render: (row) => new Date(row.timestamp).toLocaleString() }, { key: 'actor', label: 'Actor' }, { key: 'module', label: 'Module', render: (row) => label(row.module) }, { key: 'action', label: 'Action', render: (row) => <span className="font-mono text-xs">{row.action}</span> }, { key: 'ip', label: 'IP' }]} emptyLabel="No identity events recorded yet" /></CardBody></Card>
  const content = { employees: renderEmployees, organization: renderOrganization, roles: renderRoles, permissions: renderPermissions, attendance: renderAttendance, leave: renderLeave, performance: renderPerformance, audit: renderAudit }[mode]
  return <div className="space-y-6 pb-8"><PageHeader eyebrow={`${dept.code} · Workforce & Identity`} title={title} description={description} />{content?.()}<Modal open={inviteOpen} onClose={() => setInviteOpen(false)} title="Invite department employee" footer={<><Button variant="ghost" onClick={() => setInviteOpen(false)}>Cancel</Button><Button form="employee-invite" type="submit" icon={Plus}>Send invitation</Button></>}><form id="employee-invite" onSubmit={submitInvite} className="grid gap-3 sm:grid-cols-2">{[['name', 'Full name'], ['email', 'Official email'], ['designation', 'Designation'], ['office', 'Office'], ['block', 'Block']].map(([key, placeholder]) => <input key={key} required={['name', 'email'].includes(key)} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={placeholder} className="rounded-lg border border-ink-200 px-3 py-2 text-sm" />)}<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="rounded-lg border border-ink-200 px-3 py-2 text-sm">{roles.map((role) => <option key={role.id} value={role.id}>{label(role.name)}</option>)}</select><select value={form.managerId} onChange={(event) => setForm({ ...form, managerId: event.target.value })} className="rounded-lg border border-ink-200 px-3 py-2 text-sm"><option value="">Reports to department head</option>{staff.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></form></Modal></div>
}
