import { useMemo, useState } from 'react'
import { CheckCircle2, Send, Star } from 'lucide-react'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import { useAuthStore } from '../../app/store/authStore'
import { useComplaintEngine } from '../../app/store/complaintEngine'
import { CitizenComplaintRepository } from './repositories/CitizenComplaintRepository'

const TABS = ['Overview', 'Timeline', 'Photos', 'Messages', 'Feedback']

export default function CitizenComplaintDetail({ complaintId, onClose }) {
  const user = useAuthStore((state) => state.user); const complaints = useComplaintEngine((state) => state.complaints); const audits = useComplaintEngine((state) => state.auditLogs)
  const submitVerification = useComplaintEngine((state) => state.submitCitizenVerification); const escalate = useComplaintEngine((state) => state.escalateCitizenComplaint)
  const [tab, setTab] = useState('Overview'); const [rating, setRating] = useState(5); const [comment, setComment] = useState(''); const [reworkReason, setReworkReason] = useState('Issue still exists'); const [message, setMessage] = useState(''); const [messages, setMessages] = useState([])
  const raw = complaints.find((item) => item.id === complaintId); const complaint = raw && CitizenComplaintRepository.present(raw)
  const timeline = useMemo(() => raw ? CitizenComplaintRepository.timeline(raw, audits.filter((entry) => entry.complaintId === raw.id)) : [], [raw, audits])
  if (!raw || !complaint) return null
  const feedback = (satisfied) => { if (submitVerification(raw.id, user, { satisfied, rating, comment, reason: reworkReason })) onClose?.() }
  return <div className="card bg-white rounded-2xl overflow-hidden max-h-[88vh] flex flex-col">
    <header className="p-4 bg-ink-950 text-white flex justify-between gap-3"><div><h2 className="font-semibold">{complaint.title}</h2><p className="font-mono text-xs text-ink-300 mt-1">Tracking number: {complaint.trackingCode}</p></div><div className="flex items-start gap-2"><Badge tone={complaint.needsVerification ? 'warning' : complaint.status === 'Closed' ? 'positive' : 'info'}>{complaint.status}</Badge>{onClose && <button onClick={onClose}>×</button>}</div></header>
    <nav className="px-3 bg-ink-50 border-b flex gap-1 overflow-x-auto">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`px-3 py-2.5 text-xs font-semibold whitespace-nowrap border-b-2 ${tab === item ? 'border-saffron-500 text-saffron-700' : 'border-transparent text-ink-500'}`}>{item}</button>)}</nav>
    <main className="p-5 overflow-y-auto space-y-4 text-sm">
      {tab === 'Overview' && <><div className="grid grid-cols-2 gap-3"><div className="p-3 bg-ink-50 rounded-xl"><span className="text-xs text-ink-400 block">Current status</span><b>{complaint.status}</b></div><div className="p-3 bg-ink-50 rounded-xl"><span className="text-xs text-ink-400 block">Expected resolution</span><b>{new Date(complaint.expectedCompletion).toLocaleDateString()}</b></div></div><p className="text-ink-700">{complaint.description}</p><p className="text-xs text-ink-500">Location: {complaint.location.village}, {complaint.location.ward} · {complaint.location.landmark}</p>{complaint.needsVerification && <div className="p-4 bg-leaf-50 border border-leaf-200 rounded-xl"><b className="flex gap-2 items-center"><CheckCircle2 size={17} /> Work has been completed</b><p className="mt-1 text-xs">Please check the photos and let us know whether the issue is resolved.</p><Button className="mt-3" size="sm" onClick={() => setTab('Feedback')}>Verify resolution</Button></div>}</>}
      {tab === 'Timeline' && timeline.map((entry, index) => <div key={`${entry.title}-${index}`} className="flex gap-3"><div className="h-6 w-6 rounded-full bg-saffron-100 text-saffron-800 grid place-items-center text-xs">{index + 1}</div><div><b>{entry.title}</b><p className="text-xs text-ink-400">{new Date(entry.at).toLocaleString()}</p></div></div>)}
      {tab === 'Photos' && <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[['Your photos', complaint.photos.before], ['Completion photos', complaint.photos.after]].map(([label, photos]) => <div key={label}><b className="text-xs">{label}</b>{photos.length ? photos.map((photo) => <img key={photo} src={photo} alt={label} className="mt-2 rounded-xl w-full h-44 object-cover" />) : <p className="mt-2 text-xs text-ink-400">No photos available yet.</p>}</div>)}</div>}
      {tab === 'Messages' && <><div className="space-y-2">{messages.length ? messages.map((item) => <div key={item.id} className="p-3 bg-ink-50 rounded-xl">You: {item.text}</div>) : <p className="text-ink-500 text-xs">Send a question or update about this complaint.</p>}</div><div className="flex gap-2"><input className="input-field" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a message…"/><Button icon={Send} onClick={() => { if (message.trim()) { setMessages([...messages, { id: Date.now(), text: message }]); setMessage('') } }}>Send</Button></div></>}
      {tab === 'Feedback' && (complaint.needsVerification ? <div className="space-y-4"><div><b>Are you satisfied with the completed work?</b><p className="text-xs text-ink-500 mt-1">Your feedback is required before this complaint can be closed.</p></div><div><span className="text-xs font-semibold">Rate your experience</span><div className="flex gap-1 mt-1">{[1,2,3,4,5].map((star) => <button key={star} onClick={() => setRating(star)} className={star <= rating ? 'text-saffron-500' : 'text-ink-200'}><Star size={22} fill="currentColor" /></button>)}</div></div><select className="input-field" value={reworkReason} onChange={(event) => setReworkReason(event.target.value)}>{['Issue still exists', 'Work incomplete', 'Wrong location', 'Poor quality', 'Officer never visited', 'Other'].map((reason) => <option key={reason}>{reason}</option>)}</select><textarea className="input-field" rows="3" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Optional comments"/><div className="flex flex-wrap gap-2"><Button variant="positive" onClick={() => feedback(true)}>Satisfied — close complaint</Button><Button variant="outline" onClick={() => feedback(false)}>Need rework</Button>{complaint.canEscalate && <Button variant="danger" onClick={() => escalate(raw.id, user, reworkReason)}>Escalate</Button>}</div></div> : <p className="text-ink-500">Feedback will be available once the work is completed.</p>)}
    </main>
  </div>
}
